### ISSUE TITLE
Could you please give some advice about more scalable algorithms for PPR and the heat kernel?

### ISSUE THREAD

**Issue by JiaLonghao1997** [klicperajo/gdc#10]
We want to use GDC on large graph with more than 200,000 nodes, but directly calculating T^{-1} and expm(T) is very show. 
We also notice your advice: [How to use GDC in large graph ](https://github.com/gasteigerjo/gdc/issues/6)
> For large graphs I'd recommend using more scalable algorithms for PPR and the heat kernel instead of directly calculating T^{-1} and expm(T), as we do in this repository.

We can't find the more scalable algorithms for PPR and the heat kernel in this repository.

**Comment by gasteigerjo** [comment]
Thank you for your interest! Indeed, these calculations are far too expensive for large graphs. I've implemented a fast approximation for PPR in PyG: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/transforms/gdc.py#L490
