### ISSUE TITLE
Memory-Intensive process

### ISSUE THREAD

**Issue by Mugariya** [klicperajo/gdc#11]
Hello, 

When I try to use it on my data, it is very memory intensive. Is there a way to make it take less memory?

**Comment by gasteigerjo** [comment]
The vanilla version in this repository uses the full versions of the matrix inverse for PPR and matrix exponential for the heat kernel, which are very slow and memory intense.

You likely want to use approximate versions instead. I implemented this for PPR in PyG: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/transforms/gdc.py
