### ISSUE TITLE
eps gap in config file

### ISSUE THREAD

**Issue by akajinchen** [klicperajo/gdc#12]
The eps of ppr in the config file is blank. Does it have the original value?

**Comment by gasteigerjo** [comment]
As described in the paper, the sparsification is either based on top-k _or_ on a threshold eps. The config uses top-k, as defined by the provided k. You don't need to set eps if you set k. If you set both, k will take precedent, as you can see [here](https://github.com/gasteigerjo/gdc/blob/master/data.py#L209-L216).

You can look up the best configuration we found for each model-dataset pair in Appendix B.3 of the paper.
