### ISSUE TITLE
the idea is similar with this paper?

### ISSUE THREAD

**Issue by ICDI0906** [klicperajo/gdc#2]
great paper!
I find your idea is similar to the paper: GRAPH WAVELET NEURAL NETWORK?
it also changes the eigenvalues of the Laplacian, am I right?
look forward to your reply~

**Comment by gasteigerjo** [comment]
Thank you for your interest in our method!

First of all, please note that every graph transformation changes the eigenvalues of the Laplacian. The spectral domain is just a different way of viewing the transformation. That is what we do in our spectral analysis. GDC never uses the eigenvalues directly.

The motivation behind GWNN is somewhat similar to our motivation and the wavelet transforms used by GWNN are closely related to the heat kernel, yes. However, that is where the similarity ends.

As a spectral method, the GWNN learns parameters that are specific to the observed graph, i.e. is uses separate parameters for each node, which severely limits its transferability. GDC is not specific to a graph and therefore applicable to inductive settings and cases where the underlying graph evolves. Moreover, GDC is more general and can be used with any diffusion and any GNN or graph-based model. The heat kernel is only one possible diffusion. You can also use personalized PageRank (PPR) or any other diffusion parameters θ_k you like.

PS.: imho, GitHub issues are not the appropriate channel for these kinds of questions/comments. They are meant for code/implementation issues. Please send me an e-mail in the future.

**Comment by ICDI0906** [comment]
> Thank you for your interest in our method!
> 
> First of all, please note that every graph transformation changes the eigenvalues of the Laplacian. The spectral domain is just a different way of viewing the transformation. That is what we do in our spectral analysis. GDC never uses the eigenvalues directly.
> 
> The motivation behind GWNN is somewhat similar to our motivation and the wavelet transforms used by GWNN are closely related to the heat kernel, yes. However, that is where the similarity ends.
> 
> As a spectral method, the GWNN learns parameters that are specific to the observed graph, i.e. is uses separate parameters for each node, which severely limits its transferability. GDC is not specific to a graph and therefore applicable to inductive settings and cases where the underlying graph evolves. Moreover, GDC is more general and can be used with any diffusion and any GNN or graph-based model. The heat kernel is only one possible diffusion. You can also use personalized PageRank (PPR) or any other diffusion parameters θ_k you like.
> 
> PS.: imho, GitHub issues are not the appropriate channel for these kinds of questions/comments. They are meant for code/implementation issues. Please send me an e-mail in the future.

Thanks for your detail explanation, that means a lot to me. If I have some question later, I will send e-mail to you~ ^-^
