### ISSUE TITLE
Some question about the datasets

### ISSUE THREAD

**Issue by ChenmiaoYu** [klicperajo/gdc#3]
I have to say, this is an excellent model!
but I have some questions about the datasets
1. I tried to get the co-purchase graphs AMAZON COMPUTERS and AMAZON PHOTO,but I just find this https://nijianmo.github.io/amazon/index.html,I don't know how to get these two datasets
2. and this dataset "co-author graph COAUTHOR CS",which from "Microsoft Academic Graph dataset",I want to know how to deal with it
THANKS!

**Comment by gasteigerjo** [comment]
Thank you for your interest in our research!

Our implementation is based on PyTorch geometric, which makes all of the datasets from the paper available:
- [Cora, Citeseer, and PubMed](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.Planetoid)
- [Coauthor CS](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.Coauthor)
- [Amazon Computers and Photo](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.Amazon)

In our implementation we use our own [`get_dataset`](https://github.com/klicperajo/gdc/blob/master/data.py#L19) function to load these datasets, as demonstrated in [`gdc_demo.ipynb`](https://github.com/klicperajo/gdc/blob/master/gdc_demo.ipynb).

If you want to learn about the data generation process and its origin, please look at the cited papers in our paper's appendix.
