### ISSUE TITLE
The improvement on GAT

### ISSUE THREAD

**Issue by ConanCui** [klicperajo/gdc#4]
Hi, I check the number of GAT on Pubmed is about 79.0, and the performance of GAT in the figure is about 76% which corresponds to the "None" method. And I am also curious about why GAT performed worse than GCN on CORA/CITESEER/PUBMED?

**Comment by gasteigerjo** [comment]
The fact that GAT actually performs worse than GCN in a fair and thorough experimental setup is not new. This has previously been shown e.g. in [Predict then Propagate: Graph Neural Networks meet Personalized PageRank](https://arxiv.org/abs/1810.05997) and [Pitfalls of Graph Neural Network Evaluation](https://arxiv.org/abs/1811.05868). Evaluating GNNs can be tricky, so I warmly recommend reading either the first paper's experimental section or the second paper.

This is also the reason why you will find that none of the numbers reported in this paper are just copied from the original works. As we mention in our experimental section, we run all of these methods on a consistent setup, optimized all hyperparameters ourself, and report results averaged over 100 random splits and initializations.
