### ISSUE TITLE
About the formulation

### ISSUE THREAD

**Issue by hazdzz** [klicperajo/gdc#7]
Thanks for writing such a great paper! I noticed this paper because of DCRNN(_Diffusion Convolutional Recurrent Neural Network: Data-Driven Traffic Forecasting_). The author of DCRNN first purposed Graph Diffusion Convolution(personalized PageRank). However, I found his code is wrong while I'm implementing DCRNN.

I'm so curious about your code. Here, you just show the T_rw of GDC(PPR). Is the T_rw of GDC(HK) equals to T_rw of GDC(PPR) in an undiected graph? And, why T_rw of GDC(PPR) is alpha * (I_n - (1 - alpha) * \hat{A}) instead of D^{-1} * A ? More importantly, what's the formulation of GDC(PPR)? Is it \sum^{K}_{k=0}{\theta_k * T_rw^{k} * x}?

**Comment by gasteigerjo** [comment]
GDC is different from what is used in DCRNN, even if the names somewhat coincide.

T_rw is independent of the way the \theta_k's are defined. T_rw is defined in Section 2 of the paper. However, in this implementation we use T_sym, which we found to usually perform slightly better. Note that `S = alpha * (I_n - (1 - alpha) * T)^{-1} = \sum^{\infty}_{k=0} \theta_k * T^{k}` for `\theta_k = \alpha * (1-\alpha)^k` (PPR).
