### ISSUE TITLE
Could you please provide the code for applying diffusion with GAT?

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [klicperajo/gdc#8]
Dear author,

Could you please provide the code for applying diffusion with GAT? I have tried to apply diffusion on GAT, but I can't get the performance improvement with this technique. Or could you give me some guidance or tips when using diffusion on GAT?

Best

**Comment by gasteigerjo** [comment]
We list all hyperparameters in our paper. It might be worth scanning the experimental section for anything you might have missed in your implementation. One trick is that we multiply the GDC edge weights with GAT's attention scores to get the final attention scores.
