### ISSUE TITLE
A quetion about the way that diffusion matrix is used in the graph convolution

### ISSUE THREAD

**Issue by simon-hope** [klicperajo/gdc#9]
Dear authors,

I have one question about the way that sparsified diffusion matrix is used in the subsequent graph convolution.

To my understanding, the sparsified diffusion matrix is used as a weighted adjacency matrix when calling the function GCNConv. This is indicated by the code below. Am I right?

https://github.com/gasteigerjo/gdc/blob/996bc47acffd86bc9bb1df3293c87a3c7573744f/data.py#L226

If so, then the graph convolution can be expressed as \mathbf{X}^{\prime} = \mathbf{\hat{D}}^{-1/2} \mathbf{\hat{\tilde{S}}}
\mathbf{\hat{D}}^{-1/2} \mathbf{X} \mathbf{\Theta}, in which \tilde{S} is the sparsified diffusion matrix.

However, in Eq. (3) of your paper, I learn that the diffusion matrix is equivalent to the graph filter, which shall be directly applied to multiplying the node attributes. Therefore the convolution shall be \mathbf{\tilde{S}}\mathbf{X}\mathbf{\Theta}. 

If my understanding is correct, then the question is why the latter way of convolution is not applied in your codes.

Best regards,
Simon

**Comment by gasteigerjo** [comment]
Dear Simon,

Thank you for your interest in our work! Please excuse the late response.

We describe the whole process in the paper, and step 4 in Section 4 (page 5) describes exactly the renormalization you highlight. Figure 2 shows the effect of every step in the process, including renormalization. This is consistent with the code.
